# Generated by Django 4.2.3 on 2023-10-11 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auths', '0001_initial'),
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('verification', models.JSONField(null=True)),
                ('from_address', models.CharField(max_length=200)),
                ('to_address', models.CharField(max_length=200)),
                ('from_zipcode', models.CharField(max_length=6)),
                ('to_zipcode', models.CharField(max_length=6)),
                ('product_price', models.BigIntegerField()),
                ('from_user_contact', models.BigIntegerField()),
                ('to_user_contact', models.BigIntegerField()),
                ('hbd', models.DateField()),
                ('cpd', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('asign', models.BooleanField(default=False)),
                ('collected', models.BooleanField(default=False)),
                ('route_added', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('return', 'Return'), ('transferring', 'Transferring')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_at', models.DateField(blank=True, null=True)),
                ('nearest_hub_at', models.DateField(blank=True, null=True)),
                ('out_for_delivery', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateField(blank=True, null=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.booking')),
                ('current_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hubs.hub')),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orders', models.ManyToManyField(to='product.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.JSONField(null=True)),
                ('is_routed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('method', models.CharField(choices=[('credit_card', 'Credit Card'), ('razorpay', 'RazorPay'), ('bank_transfer', 'Bank Transfer')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.order')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category'),
        ),
        migrations.AddField(
            model_name='booking',
            name='from_hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_from', to='hubs.hub'),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_to', to='hubs.hub'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
