# Generated by Django 4.2.3 on 2023-10-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='returned_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
